version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: app
    depends_on:
        - mongodb
        - web
    command: yarn dev:start
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app
  web:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: web
    command: yarn dev:assets
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app